services:
  - type: web
    name: mfi-credit-scoring-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile  # Ensure the correct path to your Dockerfile
    envVars:
      - key: PORT
        value: "10000"
    disk:
      - name: model-storage
        mountPath: /data/models
        sizeGB: 1  # Adjust as needed for persistent storage
